FROM node:25-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:25-alpine AS streaming
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist ./dist
EXPOSE 2173 9173
CMD ["node", "dist/server/index.js"]

FROM nginx:alpine AS web
COPY --from=build /app/dist /usr/share/nginx/html
